config/routes.rb
Rails.application.routes.draw do
  resources :tv_shows do
    resouces :episodes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  has_many :episodes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def create
      @tv_show = TvShow.find(params[:tv_show_id])
      @episode = @tv_show.episodes.create(episode_params)
      redirect_to tv_show_path(@tv_show)
  end

  private
  def episode_params
      params.require(:episode).permit(:episode_number, :title, :summary)
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: %i[ show edit update destroy ]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully created." }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully updated." }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: "Tv show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tv_show_params
      params.require(:tv_show).permit(:name, :summary, :release_date, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavoriteTvSeriesM9</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.datetime_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit :'Guardar' %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tv Shows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Release date</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.summary %></td>
        <td><%= tv_show.release_date %></td>
        <td><%= tv_show.rating %></td>
        <td><%= link_to 'Show', tv_show %></td>
        <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
        <td><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tv Show', new_tv_show_path %>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tv_show.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @tv_show.summary %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @tv_show.release_date %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @tv_show.rating %>
</p>

<%= link_to 'Edit', edit_tv_show_path(@tv_show) %> |
<%= link_to 'Back', tv_shows_path %>


<h2>Agregue un episodio:</h2>
<%= form_with model: [ @tv_show, @tv_show.episodes.build ] do |form| %>
    <p>
        <%= form.label :episode_number %><br>
        <%= form.number_field :episode_number %>
    </p>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :summary %><br>
        <%= form.text_area :summary %>
    </p>
    <p>
        <%= form.submit "Crear episodio"%>
    </p>
<% end %>

<!--...-->
<h2>Listado de episodios</h2>
<% @tv_show.episodes.each do |episode| %>
    <p>
        <strong>Episode number:</strong>
        <%= episode.episode_number %>
    </p>

    <p>
        <strong>Title:</strong>
        <%= episode.title %>
    </p>

    <p>
        <strong>Summary:</strong>
        <%= episode.summary %>
    </p>
<% end %>

<h2>Agregue un episodio:</h2>
<%= form_with model: [ @tv_show, @tv_show.episodes.build ] do |form| %>
    <!-- ... -->
<% end %>